source 'https://rubygems.org'
ruby '~> 2.5'

gem 'autoprefixer-rails'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'kramdown'
gem 'puma', '>= 4.3.8'
gem 'rack-jekyll'
gem 'rake'
gem 'sprockets-es6'
gem 'uglifier'
gem 'jekyll-archives'