source 'https://rubygems.org'
ruby '~> 2.5'

gem 'autoprefixer-rails'
gem 'jekyll', '>= 4.0.0'
gem 'jekyll-assets', '>= 3.0.12'
gem 'jekyll-redirect-from', '>= 0.15.0'
gem 'jekyll-sitemap', '>= 1.3.1'
gem 'kramdown', '>= 2.3.0'
gem 'puma'
gem 'rack-jekyll', '>= 0.5.0'
gem 'rake'
gem 'sprockets-es6'
gem 'uglifier'
gem 'jekyll-archives', '>= 2.2.1'