source 'https://rubygems.org'
ruby '~> 2.5'

gem 'autoprefixer-rails'
gem 'jekyll', '>= 3.9.0'
gem 'jekyll-assets'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'kramdown', '>= 2.3.1'
gem 'puma', '>= 4.3.12'
gem 'rack-jekyll'
gem 'rake', '>= 12.3.3'
gem 'sprockets-es6'
gem 'uglifier'
gem 'jekyll-archives'